name: Deploy frontend

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build frontend
        run: echo Собирается билд ФРОНТа \(прогоняются юнит тесты при сборке, запускаются линтеры\), формируется docker образ с изменения

  deploy_stage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy frontend to stage/review app
        run: echo Просходит деплой ФРОНТа